
# Site params ---------------------------
title: Zapadisk
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ".."
url: "http://zapadisk.be" # the base hostname & protocol for your site


# Site settings ---------------------------
permalink: pretty
exclude: [
        'makefile',
        'README.md',
        # 'CNAME',
    ]
# Build settings
# markdown: kramdown


# minify css from scss
# sass:
#     style: :compressed
    
# minify html ---------------------------

    # gem install jekyll-minifier
    # https://github.com/digitalsparky/jekyll-minifier

plugins:
    - jekyll-minifier

# jekyll-minifier:
    # remove_multi_spaces: true
    # remove_intertag_spaces: true